name: Build, Analyze, Scan, and Push Docker Images
on:
  push:
    branches:
      - main
jobs:
  build-analyze-scan:
    name: Build, Analyze, Scan, and Push Docker Images  
    runs-on: [Linux]
    steps:
      # Étape 1 : Récupérer le code du repository GitHub
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Étape 2 : Analyser le code avec SonarQube
      - name: Build and analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Étape 3 : Installer les dépendances du backend
      - name: Install dependencies in backend
        run: npm install
        working-directory: ./mern/backend

      # Étape 4 : Installer les dépendances du frontend
      - name: Install dependencies in frontend
        run: npm install
        working-directory: ./mern/frontend

      # Étape 5 : scanner les fichiers
      - name: Trivy and scan files
        run: trivy fs . > trivyfs.txt


      # Étape 6 : S'authentifier auprès de Dockerhub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Étape 7 : Construire et pousser l'image Docker du backend
      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mon-repo-prive:backend-latest ./mern/backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mon-repo-prive:backend-latest

      # Étape 8 : Construire et pousser l'image Docker du frontend
      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mon-repo-prive:frontend-latest ./mern/frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mon-repo-prive:frontend-latest
